/** Re-export core integrator from workspace package; web-only collision modules stay local. */
export {
  BALL_RADIUS,
  COURT_H,
  COURT_W,
  FIXED_DT,
  FLIGHT_EPSILON,
  G,
  MAX_POW,
  MIN_SHOT,
  PREVIEW_DT,
  PREVIEW_MAX_DOTS,
  PREVIEW_STEPS,
  RIM_RX,
  RIM_RY,
  SUBSTEP_EPSILON,
  WALL_REST,
  aimFrom,
  applyWallBounce,
  collideObstacles,
  collideScreenEdges,
  cloneProjectile,
  edgePad,
  hypot,
  hoopLocal,
  launchFromPull,
  maxPull,
  clamp,
  MAX_LIVE_OBSTACLES,
  netPullForHoop,
  predictPath,
  rimHit,
  segmentBounce,
  stepProjectile,
  stepProjectileSubsteps,
  throughHoop,
  type AimVector,
  type BumperObstacle,
  type Hoop,
  type LaunchImpulse,
  type NetPull,
  type Obstacle,
  type PredictDot,
  type Projectile,
  type Vec2,
  type WallHitCallback,
  type WallObstacle,
  type WallSide,
} from "@trickshot/physics";

export * from "./hoopCollision";
